[project]
name = "euler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gmpy2>=2.2.1",
    "ipython>=9.2.0",
    "numpy>=2.2.6",
]
